"""Constants for application services."""

# Photo Processing
PHOTO_PROCESSING_SOFT_TIMEOUT_SECONDS = 1500  # 25 minutes
PHOTO_PROCESSING_HARD_TIMEOUT_SECONDS = 1800  # 30 minutes
MAX_PHOTO_BATCH_SIZE = 100
THUMBNAIL_WIDTH = 300
THUMBNAIL_HEIGHT = 300

# Face Detection
MAX_FACES_PER_PHOTO = 50
MIN_FACE_QUALITY_SCORE = 0.5
MIN_FACE_SIZE_PIXELS = 20

# Database Queries
MAX_PHOTO_FETCH_LIMIT = 100000  # Reasonable upper bound for in-memory ops
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
DEFAULT_CLUSTER_LIMIT = 50
DEFAULT_CLUSTER_OFFSET = 0

# Task Retries
DEFAULT_TASK_MAX_RETRIES = 5
TASK_RETRY_BACKOFF_BASE = 2  # Exponential backoff base
TASK_RETRY_MAX_DELAY_SECONDS = 600  # 10 minutes
TASK_RETRY_INITIAL_DELAY_SECONDS = 60  # 60 seconds
TASK_SOFT_TIME_LIMIT_SECONDS = 3600  # 1 hour
TASK_HARD_TIME_LIMIT_SECONDS = 3900  # 1 hour 5 minutes

# Google Photos Sync
GOOGLE_PHOTOS_BATCH_SIZE = 50
GOOGLE_PHOTOS_MAX_ITEMS = 100000

# Connection Pool
DB_POOL_WARNING_THRESHOLD = 0.8  # 80% utilization

# Worker Settings
WORKER_PREFETCH_MULTIPLIER = 1
WORKER_MAX_TASKS_PER_CHILD = 100
TASK_RESULT_EXPIRES_SECONDS = 3600  # 1 hour

# Periodic Tasks
CLEANUP_ORPHANS_INTERVAL_SECONDS = 86400  # Daily (24 hours)
MONITOR_DB_POOL_INTERVAL_SECONDS = 60  # Every minute
STALE_TASK_TIMEOUT_SECONDS = 86400  # 24 hours

# Monitoring
TASK_DURATION_HISTOGRAM_BUCKETS = (1, 5, 10, 30, 60, 120, 300, 600, 1800, 3600)  # 1s to 1h
TASK_START_TIMES_CLEANUP_THRESHOLD = 1000  # Clean up every N tasks

# Sample Limits
RELATIONSHIP_SAMPLE_PHOTO_LIMIT = 5  # Number of sample photos for relationships
